<?php

return [
    [
        'brand_slug' => 'apple',
        'name' => 'IPHONE 17 PROMAX',
        'price' => 25000000,
        'stock' => 5,
        'image' => 'products/IPHONE 17 PROMAX.png',
        'description' => 'Iphone seri terbaru',
        'ram' => '8 GB',
        'storage' => '1 TB',
        'battery' => '5000 mAH',
    ],
    [
        'brand_slug' => 'samsung',
        'name' => 'Samsung Galaxy A25',
        'price' => 24499000,
        'stock' => 7,
        'image' => 'products/Samsung Galaxy A25.png',
        'description' => 'Samsung Galaxy S26 Ultra (rilis Februari 2026) adalah flagship premium yang mengunggulkan kamera utama 200MP dengan aperture f/1.4 yang lebih terang, chipset Snapdragon 8 Elite Gen 5, dan layar 6,9 inci. Ponsel ini berfokus pada AI,  nightography yang ditingkatkan, serta fitur unik seperti privacy display dan horizontal lock',
        'ram' => '12 GB',
        'storage' => '256 GB',
        'battery' => '5000 mAH',
    ],
    [
        'brand_slug' => 'apple',
        'name' => 'IPHONE 14 PROMAX',
        'price' => 13500000,
        'stock' => 8,
        'image' => 'products/IPHONE 14 PROMAX.png',
        'description' => 'Apple iPhone 14 Pro Max adalah smartphone flagship dari Apple yang dirilis dengan peningkatan besar di sektor kamera, performa, dan layar.\\r\\n\\r\\nDitenagai oleh chip A16 Bionic, iPhone ini menawarkan performa sangat cepat dan efisien, cocok untuk multitasking, gaming berat, hingga editing video profesional.\\r\\n\\r\\n✨ Fitur utama:\\r\\n📸 Kamera Pro 48MP dengan hasil foto lebih detail dan tajam\\r\\n🌙 Mode malam lebih optimal untuk low light\\r\\n📺 Layar Super Retina XDR 6.7 inci dengan ProMotion 120Hz\\r\\n⚡ Chip A16 Bionic (super kencang & hemat daya)\\r\\n🔋 Baterai tahan lama untuk penggunaan seharian\\r\\n🔒 Face ID & Dynamic Island (fitur interaktif notifikasi Apple)\\r\\n💡 Cocok untuk:\\r\\nKonten kreator 📷\\r\\nGaming 🎮\\r\\nFotografi & videografi 🎥\\r\\nPengguna yang butuh HP premium',
        'ram' => '6 GB',
        'storage' => '256 GB',
        'battery' => '4500 mAH',
    ],
    [
        'brand_slug' => 'apple',
        'name' => 'IPHONE 16',
        'price' => 14000000,
        'stock' => 10,
        'image' => 'products/IPHONE 16.png',
        'description' => 'Apple iPhone 16 adalah smartphone flagship terbaru dari Apple yang hadir dengan desain premium, performa super cepat, dan teknologi kamera generasi terbaru. Dibekali chipset terbaru Apple yang lebih efisien dan bertenaga, iPhone 16 mampu memberikan pengalaman multitasking, gaming, hingga editing video dengan sangat lancar.\\r\\n\\r\\nLayar Super Retina XDR yang cerah dan tajam membuat tampilan visual terlihat lebih hidup, baik saat menonton film, bermain game, maupun scrolling media sosial. Desainnya tetap elegan dengan material berkualitas tinggi yang nyaman digenggam dan memberikan kesan mewah.\\r\\n\\r\\nPada sektor kamera, iPhone 16 menawarkan peningkatan kualitas foto dan video dengan hasil lebih detail, warna natural, serta performa low-light yang semakin baik. Fitur AI terbaru juga membantu menghasilkan foto profesional hanya dengan sekali jepret.\\r\\n\\r\\nDaya tahan baterai lebih optimal sehingga dapat digunakan seharian penuh untuk aktivitas produktivitas maupun hiburan. Didukung sistem operasi iOS terbaru, iPhone 16 memberikan keamanan tinggi, performa stabil, dan ekosistem Apple yang terintegrasi dengan sangat baik.\\r\\n\\r\\nCocok untuk pengguna yang menginginkan smartphone premium dengan performa tinggi, kamera berkualitas profesional, desain modern, dan pengalaman penggunaan yang eksklusif.',
        'ram' => '8 GB',
        'storage' => '256 GB',
        'battery' => '3561 mAh',
    ],
    [
        'brand_slug' => 'xiaomi',
        'name' => 'xiaomi 14 ultra',
        'price' => 20000000,
        'stock' => 12,
        'image' => 'products/xiaomi 14 ultra.png',
        'description' => 'Xiaomi 14 Ultra adalah salah satu HP flagship terbaik dari Xiaomi\\r\\n yang fokus pada fotografi profesional dan performa ekstrem. Smartphone ini dirancang untuk pengguna yang suka fotografi, videografi, gaming berat, hingga multitasking kelas tinggi.\\r\\n\\r\\n✨ Desain & Layar\\r\\n\\r\\nXiaomi 14 Ultra memakai desain premium dengan finishing elegan dan modul kamera besar khas Leica. Layarnya menggunakan panel AMOLED LTPO 6,73 inci resolusi WQHD+ dengan refresh rate 1–120Hz adaptif, sehingga animasi terasa sangat smooth sekaligus hemat baterai. Tingkat kecerahannya mencapai 3000 nits, jadi tetap jelas saat dipakai di bawah sinar matahari.\\r\\n\\r\\n⚡ Performa\\r\\n\\r\\nHP ini ditenagai chipset Snapdragon 8 Gen 3 fabrikasi 4nm yang termasuk chipset Android tercepat saat ini. Dipadukan RAM LPDDR5X dan storage UFS 4.0, performanya sangat kencang untuk:\\r\\n\\r\\nGaming ultra setting\\r\\nEditing video 4K/8K\\r\\nMultitasking berat\\r\\nAI processing dan rendering cepat\\r\\n\\r\\nHyperOS juga terasa lebih ringan dan responsif dibanding MIUI generasi lama.\\r\\n\\r\\n📸 Kamera Leica Profesional\\r\\n\\r\\nBagian paling menarik dari Xiaomi 14 Ultra adalah kameranya. Smartphone ini memakai sistem quad camera Leica 50MP:\\r\\n\\r\\nKamera utama 1 inci Sony LYT-900\\r\\nTelephoto 75mm\\r\\nPeriscope 120mm\\r\\nUltrawide 122°\\r\\n\\r\\nKualitas fotonya sangat detail dengan warna khas Leica yang terlihat lebih natural dan profesional. Bukaan variabel f/1.63–f/4.0 membuat hasil foto malam lebih bagus dan fleksibel seperti kamera DSLR. Banyak reviewer dan pengguna menyebut kamera Xiaomi 14 Ultra sebagai salah satu kamera HP terbaik saat ini.',
        'ram' => '12 GB',
        'storage' => '512 GB',
        'battery' => '5300mAh',
    ],
    [
        'brand_slug' => 'xiaomi',
        'name' => 'redmi note 14',
        'price' => 3199000,
        'stock' => 10,
        'image' => 'products/redmi note 14.png',
        'description' => 'HP mid-range gaming dengan performa kencang dan layar AMOLED 120Hz.',
        'ram' => '8 GB',
        'storage' => '256',
        'battery' => '5110 mAh',
    ],
    [
        'brand_slug' => 'vivo',
        'name' => 'Vivo Y21d',
        'price' => 3399000,
        'stock' => 7,
        'image' => 'products/Vivo Y21d.png',
        'description' => 'Smartphone baterai jumbo untuk pemakaian harian yang tahan lama.',
        'ram' => '8 GB',
        'storage' => '256',
        'battery' => '6500 mAh',
    ],
    [
        'brand_slug' => 'oppo',
        'name' => 'OPPO Reno 12F 5G',
        'price' => 4789000,
        'stock' => 6,
        'image' => 'products/OPPO Reno 12F 5G.png',
        'description' => 'HP OPPO stylish dengan layar AMOLED 120Hz, kamera AI 50MP, dan storage besar cocok untuk gaming maupun content creator.',
        'ram' => '12 GB',
        'storage' => '512 GB',
        'battery' => '5000 mAH',
    ],
    [
        'brand_slug' => 'oppo',
        'name' => 'OPPO A5 Pro',
        'price' => 3499000,
        'stock' => 8,
        'image' => 'products/OPPO A5 Pro.png',
        'description' => 'OPPO A5 Pro cocok untuk pengguna yang mencari HP murah tetapi tetap stylish dan awet dipakai sehari-hari. Sangat cocok untuk pelajar, pekerja, maupun penggunaan sosial media.',
        'ram' => '8 GB',
        'storage' => '256 GB',
        'battery' => '5800 mAH',
    ],
    [
        'brand_slug' => 'oppo',
        'name' => 'OPPO Find X8',
        'price' => 15998999,
        'stock' => 8,
        'image' => 'products/OPPO Find X8.png',
        'description' => 'OPPO Find X8 adalah flagship premium dengan performa kelas atas untuk gaming berat, fotografi profesional, editing video, dan multitasking ekstrem. Desainnya elegan dengan build quality premium.',
        'ram' => '16 GB',
        'storage' => '512 GB',
        'battery' => '5630 mAH',
    ],
    [
        'brand_slug' => 'infinix',
        'name' => 'Infinix GT 20 Pro',
        'price' => 3555000,
        'stock' => 9,
        'image' => 'products/Infinix GT 20 Pro.png',
        'description' => 'Infinix GT 20 Pro dibuat khusus untuk gamer yang ingin performa tinggi dengan harga lebih terjangkau dibanding flagship gaming phone lainnya. Desain RGB Mecha Loop di bagian belakang membuat tampilannya sangat futuristik dan cocok untuk gaming setup.',
        'ram' => '128 GB',
        'storage' => '256 GB',
        'battery' => '5000 mAH',
    ],
    [
        'brand_slug' => 'infinix',
        'name' => 'Infinix Note 40 Pro',
        'price' => 2587000,
        'stock' => 10,
        'image' => 'products/Infinix Note 40 Pro.png',
        'description' => 'Infinix Note 40 Pro cocok untuk pengguna yang ingin desain premium dengan curved AMOLED display dan pengalaman multimedia yang nyaman. HP ini sangat cocok untuk sosial media, fotografi, dan penggunaan sehari-hari.',
        'ram' => '8 GB',
        'storage' => '256 GB',
        'battery' => '5000 mAH',
    ],
    [
        'brand_slug' => 'infinix',
        'name' => 'Infinix Hot 50 Pro Plus',
        'price' => 3000000,
        'stock' => 9,
        'image' => 'products/Infinix Hot 50 Pro Plus.png',
        'description' => 'Infinix Hot 50 Pro Plus cocok untuk pengguna yang ingin HP murah tetapi tetap modern dan powerful. Desain tipis, layar AMOLED, dan refresh rate tinggi membuat HP ini sangat worth it di kelas harga 2 jutaan.',
        'ram' => '8 GB',
        'storage' => '256 GB',
        'battery' => '5000 mAH',
    ],
    [
        'brand_slug' => 'lenovo',
        'name' => 'Lenovo Legion Y90',
        'price' => 12400000,
        'stock' => 5,
        'image' => 'products/Lenovo Legion Y90.png',
        'description' => 'Lenovo Legion Y90 merupakan gaming phone premium yang dibuat khusus untuk gamer hardcore. HP ini memiliki desain futuristik dengan RGB lighting, dual cooling fan, dan trigger ultrasonic seperti console gaming. Sangat cocok untuk PUBG Mobile, Genshin Impact, CODM, hingga emulator berat.',
        'ram' => '12 GB',
        'storage' => '256 GB',
        'battery' => '5600 mAH',
    ],
    [
        'brand_slug' => 'lenovo',
        'name' => 'Lenovo Legion Phone Pro',
        'price' => 10850000,
        'stock' => 7,
        'image' => 'products/Lenovo Legion Phone Pro.png',
        'description' => 'Lenovo Legion Phone Pro hadir dengan desain unik horizontal gaming mode dan kamera pop-up samping untuk streamer maupun content creator gaming. HP ini terkenal karena performanya yang stabil dan sistem pendinginan yang agresif.',
        'ram' => '16 GB',
        'storage' => '512 GB',
        'battery' => null,
    ],
    [
        'brand_slug' => 'lenovo',
        'name' => 'ThinkPhone 25 by motorola Lenovo',
        'price' => 10720000,
        'stock' => 5,
        'image' => 'products/ThinkPhone 25 by motorola Lenovo.png',
        'description' => 'ThinkPhone by Motorola adalah HP premium enterprise dari Lenovo yang dibuat untuk profesional dan pebisnis. Desainnya terinspirasi dari laptop Lenovo ThinkPad dengan material aramid fiber yang kuat dan elegan.',
        'ram' => '8 GB',
        'storage' => '256 GB',
        'battery' => '5000 mAH',
    ],
    [
        'brand_slug' => 'realme',
        'name' => 'Realme GT 7',
        'price' => 9399000,
        'stock' => 3,
        'image' => 'products/Realme GT 7.png',
        'description' => 'Realme GT 7 adalah HP flagship terbaru Realme yang fokus pada performa gaming dan daya tahan baterai. Cocok untuk gamer, content creator, dan pengguna berat yang membutuhkan performa tinggi sepanjang hari. Desain IceSense Graphene membuat suhu HP tetap dingin saat bermain game berat.',
        'ram' => '12 GB',
        'storage' => '256 GB',
        'battery' => '5000 mAH',
    ],
    [
        'brand_slug' => 'realme',
        'name' => 'Realme 13+ 5G',
        'price' => 3500000,
        'stock' => 8,
        'image' => 'products/Realme 13 5G.png',
        'description' => 'Realme 13+ 5G cocok untuk pengguna yang mencari HP gaming murah tetapi tetap powerful. Performa Dimensity 7300 sangat stabil untuk PUBG Mobile, Mobile Legends, CODM, hingga multitasking harian.',
        'ram' => '12 GB',
        'storage' => '256 GB',
        'battery' => '5000 mAH',
    ],
    [
        'brand_slug' => 'realme',
        'name' => 'Realme C75',
        'price' => 2400000,
        'stock' => 6,
        'image' => 'products/Realme C75.png',
        'description' => 'Realme C75 cocok untuk pengguna yang ingin HP murah dengan fitur lengkap. Memiliki desain kokoh, baterai tahan lama, dan fitur NFC yang jarang ditemukan di kelas harga 2 jutaan.',
        'ram' => '8 GB',
        'storage' => '256 GB',
        'battery' => '6000 mAH',
    ],
    [
        'brand_slug' => 'samsung2',
        'name' => 'Samsung 45W Super Fast Charger',
        'price' => 40000,
        'stock' => 92,
        'image' => 'products/Samsung 45W Super Fast Charger.png',
        'description' => 'Adaptor charger USB-C dengan teknologi Super Fast Charging 2.0. Cocok untuk Samsung Galaxy, Xiaomi, Oppo, Vivo, hingga iPhone USB-C terbaru. Mendukung pengisian cepat stabil dan memiliki proteksi overheat serta overcharge.',
        'ram' => null,
        'storage' => null,
        'battery' => null,
    ],
    [
        'brand_slug' => 'samsung',
        'name' => 'Samsung Galaxy S24',
        'price' => 12999000,
        'stock' => 8,
        'image' => 'products/Samsung Galaxy S24.jpg',
        'description' => 'Samsung Galaxy S24 hadir dengan layar Dynamic AMOLED 2X, kamera AI unggulan, dan performa smooth untuk gaming serta multitasking.',
        'ram' => '8 GB',
        'storage' => '256 GB',
        'battery' => '3900 mAh',
    ],
    [
        'brand_slug' => 'infinix',
        'name' => 'Infinix 30',
        'price' => 2899000,
        'stock' => 10,
        'image' => 'products/Infinix 30.jpg',
        'description' => 'Infinix 30 menawarkan desain modern, baterai tahan lama, dan performa baik untuk penggunaan sosial media serta multimedia sehari-hari.',
        'ram' => '8 GB',
        'storage' => '256 GB',
        'battery' => '5000 mAh',
    ],
    [
        'brand_slug' => 'apple',
        'name' => 'iPhone 15',
        'price' => 20999000,
        'stock' => 6,
        'image' => 'products/iPhone 15.jpg',
        'description' => 'iPhone 15 hadir dengan desain elegan, kamera ganda canggih, dan performa Apple terbaru untuk pengalaman multimedia serta produktivitas yang lancar.',
        'ram' => '8 GB',
        'storage' => '128 GB',
        'battery' => '3279 mAh',
    ],
    [
        'brand_slug' => 'oppo',
        'name' => 'OPPO Reno 12',
        'price' => 6499000,
        'stock' => 7,
        'image' => 'products/OPPO Reno 12.jpg',
        'description' => 'OPPO Reno 12 menawarkan kombinasi kamera AI, layar AMOLED, dan charging cepat untuk pengguna yang ingin smartphone stylish dan serba bisa.',
        'ram' => '8 GB',
        'storage' => '256 GB',
        'battery' => '5000 mAh',
    ],
    [
        'brand_slug' => 'vivo',
        'name' => 'Vivo V30',
        'price' => 3799000,
        'stock' => 8,
        'image' => 'products/Vivo V30.jpg',
        'description' => 'Vivo V30 hadir dengan layar AMOLED besar, desain tipis, dan kamera selfie yang kuat untuk konten kreator serta penggunaan harian.',
        'ram' => '8 GB',
        'storage' => '128 GB',
        'battery' => '4500 mAh',
    ],
    [
        'brand_slug' => 'anker',
        'name' => 'Soundcore R60i NC by Anker',
        'price' => 398000,
        'stock' => 20,
        'image' => 'products/Soundcore R60i NC by Anker.jpg',
        'description' => 'Soundcore R60i NC by Anker menawarkan kualitas suara yang luar biasa dengan teknologi noise cancellation, cocok untuk penggunaan sehari-hari dan perjalanan.',
        'ram' => null,
        'storage' => null,
        'battery' => null,
    ],
    [
        'brand_slug' => 'baseus',
        'name' => 'TWS Baseus Encok WM01',
        'price' => 187290,
        'stock' => 15,
        'image' => 'products/TWS Baseus Encok WM01.jpg',
        'description' => 'TWS Baseus Encok WM01 menawarkan kualitas suara yang luar biasa dengan teknologi noise cancellation, cocok untuk penggunaan sehari-hari dan perjalanan.',
        'ram' => null,
        'storage' => null,
        'battery' => null,
    ],
    [
        'brand_slug' => 'baseus',
        'name' => 'Baseus Kabel Type-C ke Type-C Tungsten Gold 240W',
        'price' => 165226,
        'stock' => 15,
        'image' => 'products/Baseus Kabel Type-C ke Type-C Tungsten Gold 240W.jpg',
        'description' => 'Baseus Kabel Type-C ke Type-C Tungsten Gold 240W menawarkan kualitas dan daya tahan yang superior, cocok untuk penggunaan sehari-hari dan perjalanan.',
        'ram' => null,
        'storage' => null,
        'battery' => null,
    ],
    [
        'brand_slug' => 'mixio',
        'name' => 'MIXIO-T9/T10 Wireless Microphone Lavalier',
        'price' => 213220,
        'stock' => 15,
        'image' => 'products/MIXIO-T9_T10 Wireless Microphone Lavalier.jpg',
        'description' => 'MIXIO-T9/T10 Wireless Microphone Lavalier menawarkan kualitas suara yang luar biasa dengan teknologi wireless, cocok untuk penggunaan sehari-hari dan perjalanan.',
        'ram' => null,
        'storage' => null,
        'battery' => null,
    ],
];
