<?php

return [
    [
        'brand_slug' => 'apple',
        'name' => 'IPHONE 17 PROMAX',
        'price' => 25000000,
        'stock' => 5,
        'image' => 'products/xZl7r193Q7UiBSZNhbckE4K9lXiwcw6Jj2Swkgxj.png',
        'description' => 'Iphone seri terbaru',
        'ram' => '8 GB',
        'storage' => '1 TB',
        'battery' => '5000 mAH',
    ],
    [
        'brand_slug' => 'apple',
        'name' => 'IPHONE 16',
        'price' => 14000000,
        'stock' => 10,
        'image' => 'products/mWKlLBbYVEmSByDD5YfVCKuERTVTeuejBJnclYJo.png',
        'description' => 'Apple iPhone 16 adalah smartphone flagship terbaru dari Apple yang hadir dengan desain premium, performa super cepat, dan teknologi kamera generasi terbaru. Dibekali chipset terbaru Apple yang lebih efisien dan bertenaga, iPhone 16 mampu memberikan pengalaman multitasking, gaming, hingga editing video dengan sangat lancar.\\r\\n\\r\\nLayar Super Retina XDR yang cerah dan tajam membuat tampilan visual terlihat lebih hidup, baik saat menonton film, bermain game, maupun scrolling media sosial. Desainnya tetap elegan dengan material berkualitas tinggi yang nyaman digenggam dan memberikan kesan mewah.\\r\\n\\r\\nPada sektor kamera, iPhone 16 menawarkan peningkatan kualitas foto dan video dengan hasil lebih detail, warna natural, serta performa low-light yang semakin baik. Fitur AI terbaru juga membantu menghasilkan foto profesional hanya dengan sekali jepret.\\r\\n\\r\\nDaya tahan baterai lebih optimal sehingga dapat digunakan seharian penuh untuk aktivitas produktivitas maupun hiburan. Didukung sistem operasi iOS terbaru, iPhone 16 memberikan keamanan tinggi, performa stabil, dan ekosistem Apple yang terintegrasi dengan sangat baik.\\r\\n\\r\\nCocok untuk pengguna yang menginginkan smartphone premium dengan performa tinggi, kamera berkualitas profesional, desain modern, dan pengalaman penggunaan yang eksklusif.',
        'ram' => '8 GB',
        'storage' => '256 GB',
        'battery' => '3561 mAh',
    ],
    [
        'brand_slug' => 'xiaomi',
        'name' => 'xiaomi 14 ultra',
        'price' => 20000000,
        'stock' => 12,
        'image' => 'images/products/DDRPGL2sJwmgwgmjFKrk63aORioUARgwE5AIHFr8.png',
        'description' => 'Xiaomi 14 Ultra adalah salah satu HP flagship terbaik dari Xiaomi\\r\\n yang fokus pada fotografi profesional dan performa ekstrem. Smartphone ini dirancang untuk pengguna yang suka fotografi, videografi, gaming berat, hingga multitasking kelas tinggi.\\r\\n\\r\\n✨ Desain & Layar\\r\\n\\r\\nXiaomi 14 Ultra memakai desain premium dengan finishing elegan dan modul kamera besar khas Leica. Layarnya menggunakan panel AMOLED LTPO 6,73 inci resolusi WQHD+ dengan refresh rate 1–120Hz adaptif, sehingga animasi terasa sangat smooth sekaligus hemat baterai. Tingkat kecerahannya mencapai 3000 nits, jadi tetap jelas saat dipakai di bawah sinar matahari.\\r\\n\\r\\n⚡ Performa\\r\\n\\r\\nHP ini ditenagai chipset Snapdragon 8 Gen 3 fabrikasi 4nm yang termasuk chipset Android tercepat saat ini. Dipadukan RAM LPDDR5X dan storage UFS 4.0, performanya sangat kencang untuk:\\r\\n\\r\\nGaming ultra setting\\r\\nEditing video 4K/8K\\r\\nMultitasking berat\\r\\nAI processing dan rendering cepat\\r\\n\\r\\nHyperOS juga terasa lebih ringan dan responsif dibanding MIUI generasi lama.\\r\\n\\r\\n📸 Kamera Leica Profesional\\r\\n\\r\\nBagian paling menarik dari Xiaomi 14 Ultra adalah kameranya. Smartphone ini memakai sistem quad camera Leica 50MP:\\r\\n\\r\\nKamera utama 1 inci Sony LYT-900\\r\\nTelephoto 75mm\\r\\nPeriscope 120mm\\r\\nUltrawide 122°\\r\\n\\r\\nKualitas fotonya sangat detail dengan warna khas Leica yang terlihat lebih natural dan profesional. Bukaan variabel f/1.63–f/4.0 membuat hasil foto malam lebih bagus dan fleksibel seperti kamera DSLR. Banyak reviewer dan pengguna menyebut kamera Xiaomi 14 Ultra sebagai salah satu kamera HP terbaik saat ini.',
        'ram' => '12 GB',
        'storage' => '512 GB',
        'battery' => '5300mAh',
    ],
    [
        'brand_slug' => 'xiaomi',
        'name' => 'redmi note 14',
        'price' => 3199000,
        'stock' => 10,
        'image' => 'products/Hdme4NH6wQAYIWMga3tMPn9qxc3eT8lYYHrqiSi5.png',
        'description' => 'HP mid-range gaming dengan performa kencang dan layar AMOLED 120Hz.',
        'ram' => '8 GB',
        'storage' => '256',
        'battery' => '5110 mAh',
    ],
    [
        'brand_slug' => 'vivo',
        'name' => 'Vivo Y21d',
        'price' => 3399000,
        'stock' => 7,
        'image' => 'products/J8yfOsd57NysjCE64AQ8nW34oz4iWDNnqZYhvIYm.png',
        'description' => 'Smartphone baterai jumbo untuk pemakaian harian yang tahan lama.',
        'ram' => '8 GB',
        'storage' => '256',
        'battery' => '6500 mAh',
    ],
    [
        'brand_slug' => 'oppo',
        'name' => 'OPPO Reno 12F 5G',
        'price' => 4789000,
        'stock' => 6,
        'image' => 'products/dN94ybdIayRyiWa3w6l7xFtjCt3awsQTGSR9OX7Z.png',
        'description' => 'HP OPPO stylish dengan layar AMOLED 120Hz, kamera AI 50MP, dan storage besar cocok untuk gaming maupun content creator.',
        'ram' => '12 GB',
        'storage' => '512 GB',
        'battery' => '5000 mAH',
    ],
    [
        'brand_slug' => 'oppo',
        'name' => 'OPPO A5 Pro',
        'price' => 3499000,
        'stock' => 8,
        'image' => 'products/T4INr5Q58jRifcVDcNe9RVi6zMCBVWKSWOh14T8y.png',
        'description' => 'OPPO A5 Pro cocok untuk pengguna yang mencari HP murah tetapi tetap stylish dan awet dipakai sehari-hari. Sangat cocok untuk pelajar, pekerja, maupun penggunaan sosial media.',
        'ram' => '8 GB',
        'storage' => '256 GB',
        'battery' => '5800 mAH',
    ],
    [
        'brand_slug' => 'oppo',
        'name' => 'OPPO Find X8',
        'price' => 15998999,
        'stock' => 8,
        'image' => 'products/6RPFEusrfDRt8CoMOV2Ua5VI2aRmBW2wSYH4O5T1.png',
        'description' => 'OPPO Find X8 adalah flagship premium dengan performa kelas atas untuk gaming berat, fotografi profesional, editing video, dan multitasking ekstrem. Desainnya elegan dengan build quality premium.',
        'ram' => '16 GB',
        'storage' => '512 GB',
        'battery' => '5630 mAH',
    ],
    [
        'brand_slug' => 'infinix',
        'name' => 'Infinix GT 20 Pro',
        'price' => 3555000,
        'stock' => 9,
        'image' => 'products/D2B5saBHqeJDRmKxhBbjAcvTNn1wIwJgxnAyOj7e.png',
        'description' => 'Infinix GT 20 Pro dibuat khusus untuk gamer yang ingin performa tinggi dengan harga lebih terjangkau dibanding flagship gaming phone lainnya. Desain RGB Mecha Loop di bagian belakang membuat tampilannya sangat futuristik dan cocok untuk gaming setup.',
        'ram' => '128 GB',
        'storage' => '256 GB',
        'battery' => '5000 mAH',
    ],
    [
        'brand_slug' => 'infinix',
        'name' => 'Infinix Note 40 Pro',
        'price' => 2587000,
        'stock' => 10,
        'image' => 'products/4b41vu5x8QzLj2vpthXsz5quSCXBvIFxQelnDoGx.png',
        'description' => 'Infinix Note 40 Pro cocok untuk pengguna yang ingin desain premium dengan curved AMOLED display dan pengalaman multimedia yang nyaman. HP ini sangat cocok untuk sosial media, fotografi, dan penggunaan sehari-hari.',
        'ram' => '8 GB',
        'storage' => '256 GB',
        'battery' => '5000 mAH',
    ],
    [
        'brand_slug' => 'infinix',
        'name' => 'Infinix Hot 50 Pro Plus',
        'price' => 3000000,
        'stock' => 9,
        'image' => 'products/t5gOZVqHos9hsj9mfuNA3kdTAwmazOpHpbI0cnBH.png',
        'description' => 'Infinix Hot 50 Pro Plus cocok untuk pengguna yang ingin HP murah tetapi tetap modern dan powerful. Desain tipis, layar AMOLED, dan refresh rate tinggi membuat HP ini sangat worth it di kelas harga 2 jutaan.',
        'ram' => '8 GB',
        'storage' => '256 GB',
        'battery' => '5000 mAH',
    ],
    [
        'brand_slug' => 'lenovo',
        'name' => 'Lenovo Legion Y90',
        'price' => 12400000,
        'stock' => 5,
        'image' => 'products/tQqpybJrxpxB6DJ0upSrfJ1CtpR973dNHI2QMJkO.png',
        'description' => 'Lenovo Legion Y90 merupakan gaming phone premium yang dibuat khusus untuk gamer hardcore. HP ini memiliki desain futuristik dengan RGB lighting, dual cooling fan, dan trigger ultrasonic seperti console gaming. Sangat cocok untuk PUBG Mobile, Genshin Impact, CODM, hingga emulator berat.',
        'ram' => '12 GB',
        'storage' => '256 GB',
        'battery' => '5600 mAH',
    ],
    [
        'brand_slug' => 'lenovo',
        'name' => 'Lenovo Legion Phone Pro',
        'price' => 10850000,
        'stock' => 7,
        'image' => 'products/WrKxdqvIa8xopD36ub6W96Ft4gCfFvM03jectLEQ.png',
        'description' => 'Lenovo Legion Phone Pro hadir dengan desain unik horizontal gaming mode dan kamera pop-up samping untuk streamer maupun content creator gaming. HP ini terkenal karena performanya yang stabil dan sistem pendinginan yang agresif.',
        'ram' => '16 GB',
        'storage' => '512 GB',
        'battery' => null,
    ],
    [
        'brand_slug' => 'lenovo',
        'name' => 'Motorola ThinkPhone by Lenovo',
        'price' => 10720000,
        'stock' => 5,
        'image' => 'products/dAySHrPNRh9YDOt3Gpn5rZzFED1b6hemIwJaHuZk.png',
        'description' => 'ThinkPhone by Motorola adalah HP premium enterprise dari Lenovo yang dibuat untuk profesional dan pebisnis. Desainnya terinspirasi dari laptop Lenovo ThinkPad dengan material aramid fiber yang kuat dan elegan.',
        'ram' => '8 GB',
        'storage' => '256 GB',
        'battery' => '5000 mAH',
    ],
    [
        'brand_slug' => 'realme',
        'name' => 'Realme GT 7',
        'price' => 9399000,
        'stock' => 3,
        'image' => 'products/ZF3GsU4OhXsCK5EO2wW04BFuW2QDBH6cB2I8fIQb.png',
        'description' => 'Realme GT 7 adalah HP flagship terbaru Realme yang fokus pada performa gaming dan daya tahan baterai. Cocok untuk gamer, content creator, dan pengguna berat yang membutuhkan performa tinggi sepanjang hari. Desain IceSense Graphene membuat suhu HP tetap dingin saat bermain game berat.',
        'ram' => '12 GB',
        'storage' => '256 GB',
        'battery' => '5000 mAH',
    ],
    [
        'brand_slug' => 'realme',
        'name' => 'Realme 13+ 5G',
        'price' => 3500000,
        'stock' => 8,
        'image' => 'products/UOpywHO8DfcdEVn44KFNnUcQVZtl2SC5nGtNgpij.png',
        'description' => 'Realme 13+ 5G cocok untuk pengguna yang mencari HP gaming murah tetapi tetap powerful. Performa Dimensity 7300 sangat stabil untuk PUBG Mobile, Mobile Legends, CODM, hingga multitasking harian.',
        'ram' => '12 GB',
        'storage' => '256 GB',
        'battery' => '5000 mAH',
    ],
    [
        'brand_slug' => 'realme',
        'name' => 'Realme C75',
        'price' => 2400000,
        'stock' => 6,
        'image' => 'products/UlQZ1TzoYAip4kC719BlQYAD2AgfD1Su27sc1Qdf.png',
        'description' => 'Realme C75 cocok untuk pengguna yang ingin HP murah dengan fitur lengkap. Memiliki desain kokoh, baterai tahan lama, dan fitur NFC yang jarang ditemukan di kelas harga 2 jutaan.',
        'ram' => '8 GB',
        'storage' => '256 GB',
        'battery' => '6000 mAH',
    ],
];
